In [11]:
#Create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

import numpy as v

A = v.array([4,2,7]) 
B = v.array([6,2,5]) 

print("Is A greater than B : ", v.greater(A,B)) 
print("Is A greater_equal than B : ", v.greater_equal(A,B)) 
print("Is A Less than B : ", v.less(A,B)) 
print("Is A Less_equal than B : ", v.less_equal(A,B)) 






Is A greater than B :  [False False  True]
Is A greater_equal than B :  [False  True  True]
Is A Less than B :  [ True False False]
Is A Less_equal than B :  [ True  True False]


In [12]:
#Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

import numpy as np

array=np.zeros(10)
print("The array of 10 Zeros")
print(array)
array=np.ones(10)
print("The array of 10 Ones")
print(array)
array=np.ones(10)*5
print("The Array of the 10 Fives")
print(array)

The array of 10 Zeros
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
The array of 10 Ones
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
The Array of the 10 Fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [14]:
#Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a
#given array

import numpy as np

A = np.array([[7,3],[4,3]])
print("The Given Array:")
print(A)

print("Sum of all elements of Array:")
print(np.sum(A))

print("Sum of each column in Array:")
print(np.sum(A, axis=0))
print("Sum of each row in Array:")
print(np.sum(A, axis=1))

The Given Array:
[[7 3]
 [4 3]]
Sum of all elements of Array:
17
Sum of each column in Array:
[11  6]
Sum of each row in Array:
[10  7]


In [36]:
#Write a NumPy program to add, subtract, multiply, divide arguments element-wise.

import numpy as np 
a = np.arange(9, dtype = np.float_).reshape(3,3) 

print ("First array is:") 
print (a) 
print ("\n") 

print ("Second array is:") 
b = np.array([10,10,10]) 
print (b) 
print ("\n")   

print("Addition of the two arrays:") 
print (np.add(a,b))
print ("\n")  

print ("Subtraction the two arrays:")
print (np.subtract(a,b)) 
print ("\n")   

print ("Multiplication the two arrays: ") 
print (np.multiply(a,b))
print ("\n")  

print ("Division the two arrays: ")
print (np.divide(a,b))

First array is:
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second array is:
[10 10 10]


Addition of the two arrays:
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtraction the two arrays:
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiplication the two arrays: 
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Division the two arrays: 
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


In [23]:
#Write a NumPy program to compute the trigonometric sine, cosine and tangent array of angles given in
#degree.

import numpy as np 
s = np.array([0,30,45,60,90]) 

print ("Sine Array of  angles:")

print (np.sin(s*np.pi/180)) 
print ("\n")  

print ("Cosine values for angles in array:")
print (np.cos(s*np.pi/180)) 
print ("\n")  

print ("Tangent values for given angles:") 
print (np.tan(s*np.pi/180)) 

Sine Array of  angles:
[0.         0.5        0.70710678 0.8660254  1.        ]


Cosine values for angles in array:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Tangent values for given angles:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [25]:
#Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the
#index labels

import pandas as pd
import numpy as np

exam_data  = {'Name': ['Vishal', 'Pooja', 'Samir', 'James', 'Vikas', 'Michael', 'Sandip', 'Bhushan', 'Kevin', 'Jonas'],
        'Marks': [90, 75, 45, np.nan, 40, 20, 70, np.nan, 80, 20],
        'Attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'Qualify': ['yes', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print(df)

      Name  Marks  Attempts Qualify
a   Vishal   90.0         1     yes
b    Pooja   75.0         3     yes
c    Samir   45.0         2     yes
d    James    NaN         3      no
e    Vikas   40.0         2      no
f  Michael   20.0         3     yes
g   Sandip   70.0         1     yes
h  Bhushan    NaN         1      no
i    Kevin   80.0         2      no
j    Jonas   20.0         1     yes


In [35]:
#Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame

import pandas as pd
import numpy as np

exam_data  = {'name': ['Ana', 'Dima', 'Kathe', 'James', 'mily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("Select specific columns:")
print(df[['name', 'score']])

Select specific columns:
      name  score
a      Ana   12.5
b     Dima    9.0
c    Kathe   16.5
d    James    NaN
e     mily    9.0
f  Michael   20.0
g  Matthew   14.5
h    Laura    NaN
i    Kevin    8.0
j    Jonas   19.0


In [27]:
#Write a Pandas program to join the two given dataframes along rows and assign all data.

import pandas as pd


data1 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S3'],
         'name': ['Vishal', 'Pooja', 'Viren'], 
        'marks': [200, 210, 190]})

data2 = pd.DataFrame({
        'student_id': ['S1', 'S2', 'S6'],
        'name': ['Patil', 'Suyog', 'Ajmera'], 
        'marks': [201, 200, 198]})

print("Original DataFrames:")
print(data1)
print("-------------------------------------")
print(data2)
print("\nJoin the said two dataframes along rows:")
result_data = pd.concat([data1,data2])
print(result_data)


Original DataFrames:
  student_id    name  marks
0         S1  Vishal    200
1         S2   Pooja    210
2         S3   Viren    190
-------------------------------------
  student_id    name  marks
0         S1   Patil    201
1         S2   Suyog    200
2         S6  Ajmera    198

Join the said two dataframes along rows:
  student_id    name  marks
0         S1  Vishal    200
1         S2   Pooja    210
2         S3   Viren    190
0         S1   Patil    201
1         S2   Suyog    200
2         S6  Ajmera    198


In [32]:

#Write a Pandas program to detect missing values of a given DataFrame. Display True or False

import pandas as pd
import numpy as np
pd.set_option('display.max_rows', None)

df = pd.DataFrame({
'Order_no':[70001,np.nan,70002,70004,np.nan,70005,np.nan,70010,70003,70012,np.nan,70013],
'Purchase_amt':[150.5,270.65,65.26,110.5,948.5,2400.6,5760,1983.43,2480.4,250.45, 75.29,3045.6],
'Order_date': ['2012-10-05','2012-09-10',np.nan,'2012-08-17','2012-09-10','2012-07-27','2012-09-10','2012-10-10','2012-10-10','2012-06-27','2012-08-17','2012-04-25'],
'Customer_id':[3002,3001,3001,3003,3002,3001,3001,3004,3003,3002,3001,3001],
'Salesman_id':[5002,5003,5001,np.nan,5002,5001,5001,np.nan,5003,5002,5003,np.nan]})
print("Original Orders DataFrame:")
print(df)
print("\nMissing values of the said dataframe:")
print(df.isna())

Original Orders DataFrame:
    Order_no  Purchase_amt  Order_date  Customer_id  Salesman_id
0    70001.0        150.50  2012-10-05         3002       5002.0
1        NaN        270.65  2012-09-10         3001       5003.0
2    70002.0         65.26         NaN         3001       5001.0
3    70004.0        110.50  2012-08-17         3003          NaN
4        NaN        948.50  2012-09-10         3002       5002.0
5    70005.0       2400.60  2012-07-27         3001       5001.0
6        NaN       5760.00  2012-09-10         3001       5001.0
7    70010.0       1983.43  2012-10-10         3004          NaN
8    70003.0       2480.40  2012-10-10         3003       5003.0
9    70012.0        250.45  2012-06-27         3002       5002.0
10       NaN         75.29  2012-08-17         3001       5003.0
11   70013.0       3045.60  2012-04-25         3001          NaN

Missing values of the said dataframe:
    Order_no  Purchase_amt  Order_date  Customer_id  Salesman_id
0      False         Fal

In [33]:
#Write a Pandas program to create and display a one-dimensional array-like object containing an array of
#data.

import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10,12,14,15,18])
print(ds)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
7    15
8    18
dtype: int64
